<?php 
	$type = $_REQUEST['type'];
	$str = '';
	if ($type == "home_slider") {//首页幻灯图
		$str = '{
			"data": [
        {
            "id": "130",
            "imgs": "http://static.21cake.com//upload/images/072bfeb7bc56aca9a43ef53d8939213e.jpg",
            "showOrder": "1"
        },
        {
            "id": "130",
            "imgs": "http://static.21cake.com//upload/images/46234f068db7ac5d8e8f9d7f66135b88.jpg",
            "showOrder": "2"
        },
        {
            ""id": "130",
            "imgs": "http://static.21cake.com//upload/images/f6c418fd25ed2f8555394c38b173fb42.jpg",
            "showOrder": "3"
        },
        {
            ""id": "130",
            "imgs": "http://static.21cake.com//upload/images/6d32bce3eebeedd3358372dd0b731980.jpg",
            "showOrder": "4"
        }
    	]
		}';
	}elseif ($type == "cake") {//分类-蛋糕
		$str = '{
    "code": 0, 
    "status": "ok", 
    "message": "", 
    "data": {
        "cat": {
            "name": "分类", 
            "content": [
                {
                    "name": "蛋糕", 
                    "title": "蛋糕", 
                    "description": "新鲜乳脂奶油蛋糕", 
                    "cat_ids": "2,3,4,5,6,20,49", 
                    "sort": "1"
                }
            ]
        }, 
        "tags": {
            "fa22bf77a31700498f707fc3b9d86dff": {
                "name": "口味", 
                "content": [
                    {
                        "id": "1", 
                        "name": "乳脂奶油"
                    }, 
                    {
                        "id": "2", 
                        "name": "慕斯"
                    }, 
                    {
                        "id": "3", 
                        "name": "乳酪"
                    }, 
                    {
                        "id": "5", 
                        "name": "巧克力"
                    }, 
                    {
                        "id": "6", 
                        "name": "坚果"
                    }, 
                    {
                        "id": "7", 
                        "name": "水果"
                    }, 
                    {
                        "id": "8", 
                        "name": "含酒"
                    }, 
                    {
                        "id": "9", 
                        "name": "咖啡"
                    }, 
                    {
                        "id": "4", 
                        "name": "冰淇淋"
                    }
                ]
            }
        }, 
        "goodsArr": {
            "one": {
                "name": "蛋糕", 
                "title": "蛋糕", 
                "description": "新鲜乳脂奶油蛋糕", 
                "cat_ids": "2,3,4,5,6,20,49", 
                "goods": [
                    {
                        "bn": "0629", 
                        "site_goods_id": "638", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/f5c184a98afac9e350304232c69b2bc5.jpg", 
                        "cake_goods_id": "472", 
                        "name": "芒果奶油蛋糕", 
                        "en_name": "Mango Cream Cake", 
                        "order": 44, 
                        "product_id": "9178", 
                        "price": "198.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100074, 
                        "custom_sort": "1", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "14", 
                        "site_goods_id": "276", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/2dd80e91a481dd7ab6a18c2d013718c5.jpg", 
                        "cake_goods_id": "14", 
                        "name": "花格", 
                        "en_name": "Fruit Pocket", 
                        "order": 10, 
                        "product_id": "423", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100019, 
                        "custom_sort": "2", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "40", 
                        "site_goods_id": "471", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/505c71f60ac4b3d96744a6bb54d63cb1.jpg", 
                        "cake_goods_id": "282", 
                        "name": "摩卡", 
                        "en_name": "Café Mocha", 
                        "order": 36, 
                        "product_id": "6066", 
                        "price": "398.00", 
                        "spec": "2.0磅", 
                        "has_stock": 10038, 
                        "custom_sort": "4", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "45", 
                        "site_goods_id": "542", 
                        "label": "", 
                        "cat_id": "49", 
                        "type": "normal", 
                        "img_url": "/upload/images/887535ff37a336eb09fe99170c9b3f6b.jpg", 
                        "cake_goods_id": "387", 
                        "name": "深爱百利甜情人蛋糕", 
                        "en_name": "Deep Balleys Lovers", 
                        "order": 27, 
                        "product_id": "7697", 
                        "price": "398.00", 
                        "spec": "2.0磅", 
                        "has_stock": 10095, 
                        "custom_sort": "5", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "21", 
                        "site_goods_id": "283", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/upload/images/c418d470a166128ac8f915e121bfa493.jpg", 
                        "cake_goods_id": "21", 
                        "name": "芒果慕斯", 
                        "en_name": "Mango Jerry ", 
                        "order": 9, 
                        "product_id": "641", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100050, 
                        "custom_sort": "20", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "1028", 
                        "site_goods_id": "570", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/26e5a5d8f3fa4e50580dfdc7d9574808.jpg", 
                        "cake_goods_id": "413", 
                        "name": " （撒粉生日）黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse", 
                        "order": 30, 
                        "product_id": "8138", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 10045, 
                        "custom_sort": "21", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "09", 
                        "site_goods_id": "271", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/58c4227141bbcf6efe30b5940267a1a9.jpg", 
                        "cake_goods_id": "9", 
                        "name": "榴莲飘飘", 
                        "en_name": " A Picture of Durian Grey ", 
                        "order": 7, 
                        "product_id": "263", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 92509, 
                        "custom_sort": "23", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20", 
                        "site_goods_id": "282", 
                        "label": "", 
                        "cat_id": "2", 
                        "type": "normal", 
                        "img_url": "/upload/images/a5ead52bc79022ccf30c38be37f4ac04.jpg", 
                        "cake_goods_id": "20", 
                        "name": "杰瑞", 
                        "en_name": "Jerry ", 
                        "order": 19, 
                        "product_id": "621", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100209, 
                        "custom_sort": "25", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "0610", 
                        "site_goods_id": "600", 
                        "label": "", 
                        "cat_id": "5", 
                        "type": "normal", 
                        "img_url": "/upload/images/e7c08edfd99aa8dc924c5873dc970ab0.jpg", 
                        "cake_goods_id": "451", 
                        "name": "21cake冰淇淋狂喜套餐（赠冰包）", 
                        "en_name": " 21cake", 
                        "order": 45, 
                        "product_id": "8738", 
                        "price": "468.00", 
                        "spec": "份", 
                        "has_stock": 99906, 
                        "custom_sort": "26", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "50", 
                        "site_goods_id": "588", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/327595e905e1fb3385478b4b6d2253fc.jpg", 
                        "cake_goods_id": "415", 
                        "name": "新卡", 
                        "en_name": "Cappuccino In Mind", 
                        "order": 31, 
                        "product_id": "8218", 
                        "price": "398.00", 
                        "spec": "2.0磅", 
                        "has_stock": 10009, 
                        "custom_sort": "27", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "05", 
                        "site_goods_id": "267", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/f8d71aa2fbf7ba52c3baa863603747bd.jpg", 
                        "cake_goods_id": "5", 
                        "name": "布朗尼", 
                        "en_name": "Brownie Cake ", 
                        "order": 4, 
                        "product_id": "131", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100148, 
                        "custom_sort": "29", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "29", 
                        "site_goods_id": "290", 
                        "label": "", 
                        "cat_id": "5", 
                        "type": "normal", 
                        "img_url": "/upload/images/6d3698893ae88a0a391f9b90dd02335d.jpg", 
                        "cake_goods_id": "29", 
                        "name": "桂圆冰淇淋蛋糕", 
                        "en_name": "Ice Cream Cake with Longan", 
                        "order": 33, 
                        "product_id": "771", 
                        "price": "198.00", 
                        "spec": "1.0磅", 
                        "has_stock": 1339, 
                        "custom_sort": "30", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "02", 
                        "site_goods_id": "264", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/876769ac33295fb48da37430f85067f5.jpg", 
                        "cake_goods_id": "2", 
                        "name": "布莱克", 
                        "en_name": "The Nut Job Big ", 
                        "order": 17, 
                        "product_id": "49", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 10190, 
                        "custom_sort": "31", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "03", 
                        "site_goods_id": "265", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/fbfe369538fa7968f7f2e277e9b39ceb.jpg", 
                        "cake_goods_id": "3", 
                        "name": "核桃斯诺", 
                        "en_name": "Hickory Snow", 
                        "order": 16, 
                        "product_id": "79", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100086, 
                        "custom_sort": "33", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "17", 
                        "site_goods_id": "279", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/78ad114c07704d96ac2d8123d9ae480c.jpg", 
                        "cake_goods_id": "17", 
                        "name": "黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse", 
                        "order": 1, 
                        "product_id": "537", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 101328, 
                        "custom_sort": "35", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "12", 
                        "site_goods_id": "274", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/goods/1459337079137.jpg", 
                        "cake_goods_id": "12", 
                        "name": "百利甜情人", 
                        "en_name": "Bailey\'s Love Triangle", 
                        "order": 2, 
                        "product_id": "377", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 102068, 
                        "custom_sort": "37", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "0607", 
                        "site_goods_id": "606", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/6b39236281bad53c61b826de9836e7aa.jpg", 
                        "cake_goods_id": "447", 
                        "name": "（撒粉款孙悟空）黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse", 
                        "order": 46, 
                        "product_id": "8690", 
                        "price": "398.00", 
                        "spec": "2.0磅", 
                        "has_stock": 99971, 
                        "custom_sort": "39", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "06", 
                        "site_goods_id": "268", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/fe9f6d95e37eed09a253fc8a99525a11.jpg", 
                        "cake_goods_id": "6", 
                        "name": "松仁淡奶", 
                        "en_name": "Pine Stone Cowboy", 
                        "order": 15, 
                        "product_id": "1827", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100308, 
                        "custom_sort": "39", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "31", 
                        "site_goods_id": "298", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/3723e4875bb28d90eb77cbeda8b58f55.jpg", 
                        "cake_goods_id": "55", 
                        "name": "东方栗融", 
                        "en_name": "Wall&Tree", 
                        "order": 12, 
                        "product_id": "3159", 
                        "price": "490.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100034, 
                        "custom_sort": "41", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "47", 
                        "site_goods_id": "564", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/309dbf0e879c86c629a6c82b6f760712.jpg", 
                        "cake_goods_id": "400", 
                        "name": "（新）栗蓉暗香", 
                        "en_name": "Chestnut Cream", 
                        "order": 35, 
                        "product_id": "7946", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100086, 
                        "custom_sort": "43", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "01", 
                        "site_goods_id": "263", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/c28932d6886994d259828091a579f744.jpg", 
                        "cake_goods_id": "1", 
                        "name": "朗姆芝士", 
                        "en_name": "Rum Cheese Cake", 
                        "order": 6, 
                        "product_id": "2173", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100746, 
                        "custom_sort": "45", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "0605", 
                        "site_goods_id": "604", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/e12c0a025461074e808692c1b5ed1253.jpg", 
                        "cake_goods_id": "445", 
                        "name": "撒粉款大耳朵图图黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse", 
                        "order": 48, 
                        "product_id": "8666", 
                        "price": "398.00", 
                        "spec": "2.0磅", 
                        "has_stock": 1000004, 
                        "custom_sort": "45", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "32", 
                        "site_goods_id": "286", 
                        "label": "", 
                        "cat_id": "2", 
                        "type": "normal", 
                        "img_url": "/upload/images/56222ace4ddc9d661467ce115f6b7a89.jpg", 
                        "cake_goods_id": "24", 
                        "name": "新马斯卡彭-咖啡软芝士蛋糕", 
                        "en_name": "forget Tiramisu ", 
                        "order": 11, 
                        "product_id": "695", 
                        "price": "390.00", 
                        "spec": "1.0磅", 
                        "has_stock": 99976, 
                        "custom_sort": "47", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "33", 
                        "site_goods_id": "292", 
                        "label": "", 
                        "cat_id": "2", 
                        "type": "normal", 
                        "img_url": "/upload/images/4e0f78c08578504748dc815251b49871.jpg", 
                        "cake_goods_id": "31", 
                        "name": "冻慕斯与焗芝士", 
                        "en_name": "Cool&Hot ", 
                        "order": 20, 
                        "product_id": "3089", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100269, 
                        "custom_sort": "49", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "10", 
                        "site_goods_id": "272", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/db9c0a09f65bbf3e05ef83789469d5e4.jpg", 
                        "cake_goods_id": "10", 
                        "name": "卡布其诺", 
                        "en_name": "Cappuccino", 
                        "order": 21, 
                        "product_id": "1899", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100135, 
                        "custom_sort": "49", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "35", 
                        "site_goods_id": "327", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/upload/images/d290a164f8824685201f20ebe30aaa69.jpg", 
                        "cake_goods_id": "96", 
                        "name": "百香果酸乳酪慕斯蛋糕", 
                        "en_name": "Easycake", 
                        "order": 3, 
                        "product_id": "3810", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100159, 
                        "custom_sort": "51", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G582D6388CB0FA", 
                        "site_goods_id": "507", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/b97c755b92ab5a0791cd05b16e04ee18.jpg", 
                        "cake_goods_id": "341", 
                        "name": "重组", 
                        "en_name": "Mille-feuille", 
                        "order": 32, 
                        "product_id": "8274", 
                        "price": "968.00", 
                        "spec": "1.5磅", 
                        "has_stock": 10021, 
                        "custom_sort": "53", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "36", 
                        "site_goods_id": "354", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/upload/images/4012f756d6319a7a5f45aba2e23ea637.jpg", 
                        "cake_goods_id": "132", 
                        "name": "抹茶和栗", 
                        "en_name": "Matcha & Chestnut Mousse", 
                        "order": 0, 
                        "product_id": "3648", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100055, 
                        "custom_sort": "55", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "0606", 
                        "site_goods_id": "608", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/d2b0e6d721d82eab4e21c9dea55483b4.jpg", 
                        "cake_goods_id": "446", 
                        "name": " （撒粉款黑猫警长）黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse ", 
                        "order": 47, 
                        "product_id": "8674", 
                        "price": "398.00", 
                        "spec": "2.0磅", 
                        "has_stock": 99999, 
                        "custom_sort": "56", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "27", 
                        "site_goods_id": "288", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/upload/images/c8797e7f306e5a23965a8fc9ad0e4f91.jpg", 
                        "cake_goods_id": "27", 
                        "name": "爱尔兰咖啡", 
                        "en_name": "Irish Coffee", 
                        "order": 23, 
                        "product_id": "743", 
                        "price": "260.00", 
                        "spec": "1.0磅", 
                        "has_stock": 99971, 
                        "custom_sort": "57", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "18", 
                        "site_goods_id": "280", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/296844238c878e7eae1162145a191b23.jpg", 
                        "cake_goods_id": "18", 
                        "name": "黑方", 
                        "en_name": "Black Label ", 
                        "order": 18, 
                        "product_id": "567", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100078, 
                        "custom_sort": "59", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "41", 
                        "site_goods_id": "481", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/upload/images/c2055ffac69c5e4e96f26f8d9414cc81.jpg", 
                        "cake_goods_id": "295", 
                        "name": "汉砖", 
                        "en_name": "Bricks of Ancient China", 
                        "order": 34, 
                        "product_id": "6098", 
                        "price": "98.00", 
                        "spec": "0.25磅", 
                        "has_stock": 9744, 
                        "custom_sort": "61", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "11", 
                        "site_goods_id": "273", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/c428279ffac4d47fd774751d29e0cda9.jpg", 
                        "cake_goods_id": "11", 
                        "name": "心语心愿", 
                        "en_name": "Heartfelt Wish ", 
                        "order": 13, 
                        "product_id": "347", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100342, 
                        "custom_sort": "63", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "1027", 
                        "site_goods_id": "568", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/upload/images/f2a09f555111552477aed9ed6768e7a0.jpg", 
                        "cake_goods_id": "412", 
                        "name": "（撒粉约会）黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse", 
                        "order": 29, 
                        "product_id": "8106", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 10034, 
                        "custom_sort": "65", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "42", 
                        "site_goods_id": "480", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/upload/images/441c962bf85d5fb1b5fb2f15fc0e0fbd.jpg", 
                        "cake_goods_id": "294", 
                        "name": "风乍起", 
                        "en_name": "Unexpected Wind", 
                        "order": 28, 
                        "product_id": "6090", 
                        "price": "398.00", 
                        "spec": "1.0磅", 
                        "has_stock": 10034, 
                        "custom_sort": "67", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "1030", 
                        "site_goods_id": "586", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/goods/1492746695000.jpg", 
                        "cake_goods_id": "420", 
                        "name": "（餐盘画冠军款）黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse ", 
                        "order": 42, 
                        "product_id": "8282", 
                        "price": "198.00", 
                        "spec": "1.0磅", 
                        "has_stock": 529, 
                        "custom_sort": "69", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "04", 
                        "site_goods_id": "266", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/779ffd7cec8c44e24ea0ce509306fe20.jpg", 
                        "cake_goods_id": "4", 
                        "name": "杏仁克鲁兹", 
                        "en_name": "Crumble", 
                        "order": 22, 
                        "product_id": "109", 
                        "price": "298.00", 
                        "spec": "2.0磅", 
                        "has_stock": 100060, 
                        "custom_sort": "91", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G5888150F7E2DE", 
                        "site_goods_id": "536", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/upload/images/9b2509bf4afec5960eaa9dc67a13436e.jpg", 
                        "cake_goods_id": "380", 
                        "name": "21cake便携式冰包", 
                        "en_name": "Ice bag", 
                        "order": 14, 
                        "product_id": "7625", 
                        "price": "65.00", 
                        "spec": "份", 
                        "has_stock": 334, 
                        "custom_sort": "91", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "43", 
                        "site_goods_id": "483", 
                        "label": "", 
                        "cat_id": "2", 
                        "type": "normal", 
                        "img_url": "/goods/14770358359650.jpg", 
                        "cake_goods_id": "297", 
                        "name": "21cake生日奶油蛋糕", 
                        "en_name": "Birthday Cake", 
                        "order": 43, 
                        "product_id": "6122", 
                        "price": "498.00", 
                        "spec": "0.5磅", 
                        "has_stock": false, 
                        "custom_sort": "120", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "08", 
                        "site_goods_id": "270", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/goods/14593370463186.jpg", 
                        "cake_goods_id": "8", 
                        "name": "黑森林", 
                        "en_name": "Black Forest ", 
                        "order": 37, 
                        "product_id": "227", 
                        "price": "268.00", 
                        "spec": "1.0磅", 
                        "has_stock": false, 
                        "custom_sort": "120", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "13", 
                        "site_goods_id": "275", 
                        "label": "", 
                        "cat_id": "3", 
                        "type": "normal", 
                        "img_url": "/goods/14830027254227.jpg", 
                        "cake_goods_id": "13", 
                        "name": "卡百利", 
                        "en_name": "Strawberry Fool ", 
                        "order": 25, 
                        "product_id": "395", 
                        "price": "268.00", 
                        "spec": "1.0磅", 
                        "has_stock": false, 
                        "custom_sort": "120", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "19", 
                        "site_goods_id": "281", 
                        "label": "", 
                        "cat_id": "2", 
                        "type": "normal", 
                        "img_url": "/goods/14593363138999.jpg", 
                        "cake_goods_id": "19", 
                        "name": "黑越橘", 
                        "en_name": "Blue Monday", 
                        "order": 8, 
                        "product_id": "585", 
                        "price": "268.00", 
                        "spec": "1.0磅", 
                        "has_stock": false, 
                        "custom_sort": "120", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "30", 
                        "site_goods_id": "291", 
                        "label": "", 
                        "cat_id": "4", 
                        "type": "normal", 
                        "img_url": "/goods/145933696681.jpg", 
                        "cake_goods_id": "30", 
                        "name": "中秋坚果芝士慕斯", 
                        "en_name": "The Moon Cake", 
                        "order": 5, 
                        "product_id": "2239", 
                        "price": "260.00", 
                        "spec": "1.0磅", 
                        "has_stock": false, 
                        "custom_sort": "120", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "26", 
                        "site_goods_id": "287", 
                        "label": "", 
                        "cat_id": "6", 
                        "type": "normal", 
                        "img_url": "/goods/14593369123250.jpg", 
                        "cake_goods_id": "26", 
                        "name": "平安夜", 
                        "en_name": "Silent Night ", 
                        "order": 49, 
                        "product_id": "719", 
                        "price": "198.00", 
                        "spec": "1.0磅", 
                        "has_stock": false, 
                        "custom_sort": "120", 
                        "tag_ids": ""
                    }
                ]
            }
        }
    }
}';
	}elseif ($type == "present") {//分类-设计师礼品
		$str='{
    "code": 0, 
    "status": "ok", 
    "message": "", 
    "data": {
        "cat": {
            "name": "分类", 
            "content": [
                {
                    "name": "礼品", 
                    "title": "礼品", 
                    "description": "设计师礼品专区", 
                    "cat_ids": "52", 
                    "sort": "1"
                }
            ]
        }, 
        "tags": [ ], 
        "goodsArr": {
            "1": {
                "name": "礼品", 
                "title": "礼品", 
                "description": "设计师礼品专区", 
                "cat_ids": "52", 
                "goods": [
                    {
                        "bn": "G58C249B0D6C56", 
                        "site_goods_id": "574", 
                        "label": "", 
                        "cat_id": "52", 
                        "type": "normal", 
                        "img_url": "/goods/1490576478000.jpg", 
                        "cake_goods_id": "405", 
                        "name": "设计师牛皮本", 
                        "en_name": "设计师牛皮本", 
                        "order": 1, 
                        "product_id": "8002", 
                        "price": "8.00", 
                        "spec": "个", 
                        "has_stock": 677, 
                        "custom_sort": "25", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G585CB95EA33B8", 
                        "site_goods_id": "522", 
                        "label": "", 
                        "cat_id": "52", 
                        "type": "normal", 
                        "img_url": "/goods/1489414663000.jpg", 
                        "cake_goods_id": "358", 
                        "name": "设计师关灯许愿蜡烛", 
                        "en_name": "Wishing candle", 
                        "order": 4, 
                        "product_id": "7287", 
                        "price": "60.00", 
                        "spec": "份", 
                        "has_stock": 7480, 
                        "custom_sort": "26", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G58C25615B28D7", 
                        "site_goods_id": "562", 
                        "label": "", 
                        "cat_id": "52", 
                        "type": "normal", 
                        "img_url": "/goods/1489415050000.jpg", 
                        "cake_goods_id": "408", 
                        "name": "设计师光之沙漏蜡烛", 
                        "en_name": "设计师光之沙漏蜡烛", 
                        "order": 3, 
                        "product_id": "8026", 
                        "price": "99.00", 
                        "spec": "个", 
                        "has_stock": 79996, 
                        "custom_sort": "27", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G58C248B33AC93", 
                        "site_goods_id": "560", 
                        "label": "", 
                        "cat_id": "52", 
                        "type": "normal", 
                        "img_url": "/goods/1489414467000.jpg", 
                        "cake_goods_id": "404", 
                        "name": "设计师八音盒", 
                        "en_name": "Music box", 
                        "order": 0, 
                        "product_id": "7994", 
                        "price": "80.00", 
                        "spec": "个", 
                        "has_stock": 668, 
                        "custom_sort": "29", 
                        "tag_ids": ""
                    }
                ]
            }
        }
    }
}';
	}elseif ($type == "tea") {//下午茶
		$str = '{
    "code": 0, 
    "status": "ok", 
    "message": "", 
    "data": {
        "cat": {
            "name": "分类", 
            "content": [
                {
                    "name": "小切块", 
                    "title": "小切块", 
                    "description": "55g，6种口味", 
                    "cat_ids": "37", 
                    "sort": "1"
                }, 
                {
                    "name": "常温蛋糕", 
                    "title": "常温蛋糕", 
                    "description": "方便携带，可配送至全国", 
                    "cat_ids": "36", 
                    "sort": "2"
                }, 
                {
                    "name": "冰淇淋", 
                    "title": "＋Gelato10", 
                    "description": "10天生命的意式杰拉朵冰淇淋", 
                    "cat_ids": "29,61", 
                    "sort": "3"
                }, 
                {
                    "name": "咖啡", 
                    "title": "配饮", 
                    "description": "挂耳咖啡", 
                    "cat_ids": "35", 
                    "sort": "4"
                }
            ]
        }, 
        "tags": {
            "fa22bf77a31700498f707fc3b9d86dff": {
                "name": "口味", 
                "content": [
                    {
                        "id": "1", 
                        "name": "乳脂奶油"
                    }, 
                    {
                        "id": "2", 
                        "name": "慕斯"
                    }, 
                    {
                        "id": "5", 
                        "name": "巧克力"
                    }, 
                    {
                        "id": "6", 
                        "name": "坚果"
                    }, 
                    {
                        "id": "7", 
                        "name": "水果"
                    }, 
                    {
                        "id": "9", 
                        "name": "咖啡"
                    }
                ]
            }
        }, 
        "goodsArr": {
            "one": {
                "name": "小切块", 
                "title": "小切块", 
                "description": "55g，6种口味", 
                "cat_ids": "37", 
                "goods": [
                    {
                        "bn": "G572C025163423", 
                        "site_goods_id": "409", 
                        "label": "", 
                        "cat_id": "37", 
                        "type": "normal", 
                        "img_url": "/goods/14786813791984.jpg", 
                        "cake_goods_id": "199", 
                        "name": "小切块-松仁淡奶", 
                        "en_name": "Pine Stone Cowboy", 
                        "order": 12, 
                        "product_id": "4652", 
                        "price": "36.00", 
                        "spec": "份", 
                        "has_stock": 86054, 
                        "custom_sort": "4", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G582010E585AA3", 
                        "site_goods_id": "503", 
                        "label": "", 
                        "cat_id": "37", 
                        "type": "normal", 
                        "img_url": "/goods/1478681352763.jpg", 
                        "cake_goods_id": "337", 
                        "name": "小切块-布朗尼", 
                        "en_name": "Brownie", 
                        "order": 17, 
                        "product_id": "6874", 
                        "price": "36.00", 
                        "spec": "份", 
                        "has_stock": 5041, 
                        "custom_sort": "5", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20160701", 
                        "site_goods_id": "446", 
                        "label": "", 
                        "cat_id": "37", 
                        "type": "normal", 
                        "img_url": "/goods/14684034862768.jpg", 
                        "cake_goods_id": "252", 
                        "name": "小切块-芒果慕斯", 
                        "en_name": "Mango Jerry", 
                        "order": 13, 
                        "product_id": "5433", 
                        "price": "36.00", 
                        "spec": "份", 
                        "has_stock": 94826, 
                        "custom_sort": "6", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20160631", 
                        "site_goods_id": "444", 
                        "label": "", 
                        "cat_id": "37", 
                        "type": "normal", 
                        "img_url": "/goods/14673705539744.jpg", 
                        "cake_goods_id": "250", 
                        "name": "小切块-抹茶和栗慕斯", 
                        "en_name": "Matcha & Chestnut Mousse", 
                        "order": 15, 
                        "product_id": "5393", 
                        "price": "36.00", 
                        "spec": "块", 
                        "has_stock": 95249, 
                        "custom_sort": "7", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20160630", 
                        "site_goods_id": "443", 
                        "label": "", 
                        "cat_id": "37", 
                        "type": "normal", 
                        "img_url": "/goods/14673705422468.jpg", 
                        "cake_goods_id": "249", 
                        "name": "小切块-黑白巧克力慕斯", 
                        "en_name": "Black and White Chocolate Mousse", 
                        "order": 14, 
                        "product_id": "5385", 
                        "price": "36.00", 
                        "spec": "块", 
                        "has_stock": 90420, 
                        "custom_sort": "8", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "G572C02166C107", 
                        "site_goods_id": "408", 
                        "label": "", 
                        "cat_id": "37", 
                        "type": "normal", 
                        "img_url": "/goods/14635433047528.jpg", 
                        "cake_goods_id": "198", 
                        "name": "小切块-卡布其诺", 
                        "en_name": "Cappuccino", 
                        "order": 30, 
                        "product_id": "4500", 
                        "price": "36.00", 
                        "spec": "份", 
                        "has_stock": 94936, 
                        "custom_sort": "20", 
                        "tag_ids": ""
                    }
                ]
            }, 
            "two": {
                "name": "常温蛋糕", 
                "title": "常温蛋糕", 
                "description": "方便携带，可配送至全国", 
                "cat_ids": "36", 
                "goods": [
                    {
                        "bn": "20160504", 
                        "site_goods_id": "405", 
                        "label": "", 
                        "cat_id": "36", 
                        "type": "normal", 
                        "img_url": "/goods/14624512959108.jpg", 
                        "cake_goods_id": "195", 
                        "name": "常温蛋糕-布朗尼", 
                        "en_name": "Brownie", 
                        "order": 2, 
                        "product_id": "4437", 
                        "price": "23.00", 
                        "spec": "份", 
                        "has_stock": 93845, 
                        "custom_sort": "70", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20160502", 
                        "site_goods_id": "399", 
                        "label": "", 
                        "cat_id": "36", 
                        "type": "normal", 
                        "img_url": "/goods/1462454357530.jpg", 
                        "cake_goods_id": "182", 
                        "name": "常温蛋糕-百香果", 
                        "en_name": "Passion fruit", 
                        "order": 3, 
                        "product_id": "4299", 
                        "price": "15.00", 
                        "spec": "份", 
                        "has_stock": 91106, 
                        "custom_sort": "71", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20160503", 
                        "site_goods_id": "404", 
                        "label": "", 
                        "cat_id": "36", 
                        "type": "normal", 
                        "img_url": "/goods/14624506742604.jpg", 
                        "cake_goods_id": "194", 
                        "name": "常温蛋糕-核桃", 
                        "en_name": "Juglans", 
                        "order": 4, 
                        "product_id": "4445", 
                        "price": "15.00", 
                        "spec": "份", 
                        "has_stock": 89055, 
                        "custom_sort": "72", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20170109-30", 
                        "site_goods_id": "526", 
                        "label": "", 
                        "cat_id": "36", 
                        "type": "normal", 
                        "img_url": "/goods/14824776546720.jpg", 
                        "cake_goods_id": "366", 
                        "name": "点心盒子（常温蛋糕*10，红茶*2）", 
                        "en_name": "点心盒子", 
                        "order": 11, 
                        "product_id": "7415", 
                        "price": "200.00", 
                        "spec": "盒", 
                        "has_stock": 9784, 
                        "custom_sort": "160", 
                        "tag_ids": ""
                    }
                ]
            }, 
            "three": {
                "name": "冰淇淋", 
                "title": "＋Gelato10", 
                "description": "10天生命的意式杰拉朵冰淇淋", 
                "cat_ids": "29,61", 
                "goods": [
                    {
                        "bn": "201707", 
                        "site_goods_id": "618", 
                        "label": "", 
                        "cat_id": "61", 
                        "type": "multiply", 
                        "img_url": "/upload/images/8ac4d62eac49d75862ff4b2ac6c1b768.png", 
                        "cake_goods_id": "458", 
                        "name": "牛乳冰淇淋组合（2+1）", 
                        "en_name": "Gelato10", 
                        "order": 16, 
                        "product_id": "8914", 
                        "price": "100.00", 
                        "spec": "份", 
                        "has_stock": 79999, 
                        "custom_sort": "1", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "0624", 
                        "site_goods_id": "642", 
                        "label": "", 
                        "cat_id": "29", 
                        "type": "normal", 
                        "img_url": "/upload/images/2cc91b2a50413da398075a8f5ac632c0.jpg", 
                        "cake_goods_id": "467", 
                        "name": "荔枝冰淇淋", 
                        "en_name": "Litchi Gelato", 
                        "order": 27, 
                        "product_id": "9066", 
                        "price": "45.00", 
                        "spec": "盒", 
                        "has_stock": 1034, 
                        "custom_sort": "1", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "201603", 
                        "site_goods_id": "372", 
                        "label": "", 
                        "cat_id": "29", 
                        "type": "normal", 
                        "img_url": "/upload/images/2781a9ece26660df8c305aa56a296e69.jpg", 
                        "cake_goods_id": "155", 
                        "name": "拿铁冰淇淋", 
                        "en_name": "Latte Gelato", 
                        "order": 34, 
                        "product_id": "3986", 
                        "price": "45.00", 
                        "spec": "盒", 
                        "has_stock": 2264, 
                        "custom_sort": "3", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "YWNRBQL", 
                        "site_goods_id": "373", 
                        "label": "", 
                        "cat_id": "29", 
                        "type": "normal", 
                        "img_url": "/upload/images/6a5b972b8252ce318109f9caccaba019.jpg", 
                        "cake_goods_id": "156", 
                        "name": "原味牛乳冰淇淋", 
                        "en_name": "Milk Gelato", 
                        "order": 29, 
                        "product_id": "3938", 
                        "price": "45.00", 
                        "spec": "盒", 
                        "has_stock": 1249, 
                        "custom_sort": "30", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "20160712", 
                        "site_goods_id": "449", 
                        "label": "", 
                        "cat_id": "29", 
                        "type": "normal", 
                        "img_url": "/goods/1468572870494.jpg", 
                        "cake_goods_id": "256", 
                        "name": "夏日-Affogato组合", 
                        "en_name": "Affogato", 
                        "order": 28, 
                        "product_id": "5465", 
                        "price": "55.00", 
                        "spec": "份", 
                        "has_stock": 78560, 
                        "custom_sort": "131", 
                        "tag_ids": ""
                    }
                ]
            }, 
            "four": {
                "name": "咖啡", 
                "title": "配饮", 
                "description": "挂耳咖啡", 
                "cat_ids": "35", 
                "goods": [
                    {
                        "bn": "57", 
                        "site_goods_id": "540", 
                        "label": "", 
                        "cat_id": "35", 
                        "type": "normal", 
                        "img_url": "/goods/1486465322000.jpg", 
                        "cake_goods_id": "389", 
                        "name": "（十连包）耶加雪菲挂耳咖啡", 
                        "en_name": "Yirgacheffe Coffee", 
                        "order": 24, 
                        "product_id": "7841", 
                        "price": "100.00", 
                        "spec": "盒", 
                        "has_stock": 566, 
                        "custom_sort": "50", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "56", 
                        "site_goods_id": "538", 
                        "label": "", 
                        "cat_id": "35", 
                        "type": "normal", 
                        "img_url": "/goods/1486373064000.jpg", 
                        "cake_goods_id": "388", 
                        "name": "（十连包）巴西喜拉多挂耳咖啡", 
                        "en_name": "Brazil Coffee", 
                        "order": 23, 
                        "product_id": "7761", 
                        "price": "100.00", 
                        "spec": "盒", 
                        "has_stock": 526, 
                        "custom_sort": "51", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "201607", 
                        "site_goods_id": "400", 
                        "label": "", 
                        "cat_id": "35", 
                        "type": "normal", 
                        "img_url": "/goods/14624494532004.jpg", 
                        "cake_goods_id": "183", 
                        "name": "耶加雪菲挂耳咖啡", 
                        "en_name": "Yirgacheffe Coffee", 
                        "order": 0, 
                        "product_id": "4365", 
                        "price": "10.00", 
                        "spec": "包", 
                        "has_stock": 53217, 
                        "custom_sort": "52", 
                        "tag_ids": ""
                    }, 
                    {
                        "bn": "201609", 
                        "site_goods_id": "402", 
                        "label": "", 
                        "cat_id": "35", 
                        "type": "normal", 
                        "img_url": "/goods/14624494721257.jpg", 
                        "cake_goods_id": "185", 
                        "name": "巴西喜拉多挂耳咖啡", 
                        "en_name": "Brazil Coffee", 
                        "order": 1, 
                        "product_id": "4469", 
                        "price": "10.00", 
                        "spec": "包", 
                        "has_stock": 44966, 
                        "custom_sort": "53", 
                        "tag_ids": ""
                    }
                ]
            }
        }
    }
}';
	}elseif ($type == "cart_ad") {//购物车下方广告
		$str = '{
    "code": 0, 
    "status": "ok", 
    "message": "", 
    "data": {
        "cart_bottom": [
            {
                "name": "芒果奶油蛋糕", 
                "href": "/goods-472.html", 
                "target": "_blank", 
                "img_url": "/upload/images/f5c184a98afac9e350304232c69b2bc5.jpg", 
                "sort": "1"
            }, 
            {
                "name": "Café Mocha摩卡", 
                "href": "/goods-282.html", 
                "target": "_blank", 
                "img_url": "/upload/images/505c71f60ac4b3d96744a6bb54d63cb1.jpg", 
                "sort": "2"
            }, 
            {
                "name": "Cappuccino In Mind新卡", 
                "href": "/goods-415.html", 
                "target": "_blank", 
                "img_url": "/upload/images/327595e905e1fb3385478b4b6d2253fc.jpg", 
                "sort": "3"
            }, 
            {
                "name": "Fruit Pocket 花格", 
                "href": "/goods-14.html", 
                "target": "_blank", 
                "img_url": "/upload/images/2dd80e91a481dd7ab6a18c2d013718c5.jpg", 
                "sort": "4"
            }
        ], 
        "cart_banner": [ ], 
        "cart_suggest": {
            "1": {
                "bn": "20160701", 
                "name": "小切块-芒果慕斯", 
                "spec": "份", 
                "sort": "1", 
                "price": "36.00", 
                "product_id": "5433", 
                "img_url": "/goods/14684034862768.jpg"
            }, 
            "2": {
                "bn": "20160630", 
                "name": "小切块-黑白巧克力慕斯", 
                "spec": "块", 
                "sort": "2", 
                "price": "36.00", 
                "product_id": "5385", 
                "img_url": "/goods/14673705422468.jpg"
            }
        }
    }
}';
	}elseif ($type == "cart") {//获取购物车 spec(规格)，covers（餐具数）
		$str='{
			"data": [
        {
            "id": "130",
            "imgs": "http://static.21cake.com/public/images/54/4f/63/f520f103784371df122875f84f3f5586.jpg",
            "en_name": "Matcha &amp; Chestnut Mousse",
            "ch_name":"小切块-抹茶和栗慕斯",
            "spec":"份",
            "price":"￥36.00",
            "count":"1",
            "covers":"1"
        },
        {
           "id": "130",
            "imgs": "http://static.21cake.com/public/images/24/44/4b/759067f84bebf40f09dfca20e472b52a.jpg",
            "en_name": "Square candle",
            "ch_name":"方形蜡烛",
            "spec":"个",
            "price":"￥10.00",
            "count":"2",
            "covers":"0"
        },
        {
           "id": "130",
            "imgs": "http://static.21cake.com/public/images/14/65/8a/c8566b9eac61b5568eedfcef86323b41.jpg",
            "en_name": "Deep Balleys Lovers",
            "ch_name":"深爱百利甜情人蛋糕",
            "spec":"2.0磅",
            "price":"￥398.00",
            "count":"1",
            "covers":"10"
        },
        {
            "id": "130",
            "imgs": "http://static.21cake.com/public/images/bd/ae/a9/3470792b94835528397a2f24d7d14ca4.jpg",
            "en_name": "Mango Cream Cake",
            "ch_name":"芒果奶油蛋糕",
            "spec":"5.0磅",
            "price":"￥398.00",
            "count":"1",
            "covers":"10"
        }
    	]
		}';
	}
	echo "$str";
 ?>